spring:
  liquibase:
    contexts: test
    change-log: classpath:/db/db.changelog-postgresql.xml
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://locahost:5432/postgres
    username:
    password:
decorator:
  datasource:
    enabled: true
vitality:
  debug: true