# 需要在子工程覆盖info下的参数，否则拿到的信息是这个父工程的，而不是所期待的子工程的。http://localhost:8080/actuator/info
#info:
#  app:
#    groupId: @project.groupId@
#    artifactId: @project.artifactId@
#    version: @project.version@
#    encoding: @project.build.sourceEncoding@
#    java:
#      source: @java.version@
#      target: @java.version@
#    quickboot: @quickboot.version@
#    springboot: @springboot.version@
server:
  port: 8080
  servlet:
    context-path: /
  tomcat:
    uri-encoding: UTF-8
  ssl:
    enabled: false
    # 服务端证书，单向认证
    key-store: classpath:mengweijin.jks
    # key-store: C:\Users\mengweijin\mengweijin.jks
    key-store-password: 123456
    key-store-type: JKS
    key-alias: mengweijin
    # 客户端证书认证，双向认证。可选值为：none、want 和 need
    client-auth: need
    # 这里也需要配置 mengweijin.jks 而不是 client.jks
    trust-store: classpath:mengweijin.jks
    trust-store-password: 123456
    trust-store-type: JKS
    trust-store-provider: SUN
spring:
  profiles:
    active: dev
  mvc:
    throw-exception-if-no-handler-found: false
  resources:
    # 对于Restful风格的应用应该设置为false; 对于传统的应用（如: 使用thymeleaf），应该设置为 true, 否则浏览器访问不到静态资源文件
    # 如果启用knife4j-spring-boot-starter，则需要设置为true, 否则无法正常显示接口文档
    add-mappings: true
  messages:
    # 国际化资源文件路径
    basename: i18n/messages
  jackson:
    # 默认就是UTC时区
    #time-zone: UTC
    # 加上这个配置，从前台接收LocalDateTime类型可直接使用@DateTimeFormat注解
    #date-format: yyyy-MM-dd HH:mm:ss
    # 序列化所有实体类的字段，包括值为null的
    default-property-inclusion: ALWAYS
  task:
    # @Async Spring异步任务
    execution:
      pool:
        # default 8  TaskExecutionProperties
        core-size: 8
    # scheduler Spring调度任务
    scheduling:
      pool:
        # default 1  TaskSchedulingProperties
        size: 8
# Spring Boot的actuator（健康监控）功能，访问：http://localhost:80/actuator
management:
  endpoint:
    health:
      # always / never / when-authorized
      show-details: never
  endpoints:
    web:
      exposure:
        # 要暴露出来的接口，可配置：health(默认), info（默认）, * 代表所有
        include: [ "*" ]
        #exclude: ["trace"]
      #server:
      #不配置的话默认使用应用程序下的端口
      #port: 80
      #servlet:
      # 默认即为：/actuator
    #context-path: /actuator
# http://localhost:8080/doc.html
knife4j:
  enable: true
  documents:
    - group: 1.2.x
      name: 测试自定义标题分组
      locations: classpath:md/*
  setting:
    enableSwaggerModels: true
    enableDocumentManage: true
    enableHost: false
    enableHostText: http://localhost:999
    enableRequestCache: true
    enableFilterMultipartApis: false
    enableFilterMultipartApiMethodType: POST
    language: zh-CN
  cors: false
  production: false
  basic:
    enable: false
    username: test
    password: 123
quickboot:
  # 允许跨域
  cors: true
  xss:
    # 是否启用xss过滤
    enabled: true
    # 不需要xss校验的链接（配置示例：/system/*,/tool/*）
    #excludes: /druid/*,/actuator/*